config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    mount Ckeditor::Engine => "/ckeditor"

    resources :blogs do
      resources :comments
    end

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/auth/:provider/callback", to: "sessions#create"
    get "/auth/failure", to: "sessions#failure"

    resources :blogs do
      resources :likes
      resources :comments
    end

    resources :users do
      member do
        resources :followers
        resources :following
      end
    end

    resources :places do
      resources :comments
    end

    resources :users
    resources :districts
    resources :places
    resources :blogs
    resources :bookmarks, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_tree order: "created_at ASC"
  has_one :general
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user
  before_action :load_commentable, only: :create
  before_action :correct_comment, only: :destroy

  def create
    @id = params[:comment][:parent_id].to_i

    if @id > 0
      parent = @commentable.comments.find_by(id: @id)
      @comment = parent.children.build comment_params
      @comment.user_id = current_user.id
      @comment.commentable_id = @commentable.id
      @comment.commentable_type = parent.commentable_type
    else
      @comment = @commentable.comments.build comment_params
      @comment.user_id = current_user.id
    end

    if @comment.save
      flash[:success] = t "create_success"

      if @comment.commentable_type == Settings.blog_s
        redirect_to blog_path(id: @comment.commentable_id)
      else
        redirect_to place_path(id: @comment.commentable_id)
      end
    else
      flash[:danger] = t "create_fail"
      redirect_to root_url
    end
  end

  def destroy
    @comment.descendants.each(&:destroy)

    if @comment.destroy
      flash[:success] = t "delete_success"

      if @comment.commentable_type == Settings.blog_s
        redirect_to blog_path(id: @comment.commentable_id)
      else
        redirect_to place_path(id: @comment.commentable_id)
      end
    else
      flash[:danger] = t "delete_fail"
      render root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit :content
  end

  def load_commentable
    @type = params[:comment][:type]

    @commentable = if @type == "Blog"
                     Blog.find_by id: params[:comment][:commentable_id]
                   else
                     Place.find_by id: params[:comment][:commentable_id]
                   end

    return if @commentable
    flash[:danger] = t "not_found"
    redirect_to root_url
  end

  def correct_comment
    @comment = current_user.comments.find_by id: params[:id]

    return if @comment
    flash[:danger] = t "not found"
    redirect_to root_url
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for comments, commentable, comment_new
    safe_join(comments.map do |comment, nested_comments|
      render(comment, commentable: commentable,
        comment_new: comment_new) + tree(nested_comments, commentable)
    end)
  end

  def tree nested_comments, commentable
    unless nested_comments.empty?
      content_tag :div,
        comments_tree_for(nested_comments, commentable, Comment.new),
        class: "replies"
    end
  end
end

app/views/comments/_comment.html.erb
<%= link_to comment.user.name, comment.user %>
<%= comment.content %><br>
Posted: <%= comment.created_at.strftime("%d-%m-%Y") %>
<% if comment.user == current_user %>
  <% if comment.commentable_type == "Blog" %>
    <%= link_to t(".delete"), blog_comment_path(commentable, comment),
      method: :delete, data: { confirm: t(".sure") } %>
  <% else %>
    <%= link_to t(".delete"), place_comment_path(commentable, comment),
      method: :delete, data: { confirm: t(".sure") } %>
  <% end %>
  <i class="fa fa-trash"></i>
<% end %><hr>
<% if logged_in? && comment.parent_id.nil? %>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-11">
      <%= render "comments/comment_form", commentable: commentable, parent_id: comment.id,
          comment_new: comment_new %>
    </div>
  </div>
<% end %>

app/views/comments/_comment_form.html.erb
<%= form_for [commentable, comment_new] do |f| %>
  <%= f.hidden_field :parent_id, value: parent_id %>
  <%= f.hidden_field :commentable_id, value: commentable.id %>
  <%= f.hidden_field :type, value: comment_new.commentable_type %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.text_field :content, placeholder: t(".add"), class: "form-control" %>
  <%= f.submit t(".comment"), class: "form-cmt" %>
<% end %>