config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    mount Ckeditor::Engine => "/ckeditor"

    resources :blogs do
      resources :comments
    end

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/auth/:provider/callback", to: "sessions#create"
    get "/auth/failure", to: "sessions#failure"

    resources :blogs do
      resources :likes
      resources :comments
    end

    resources :users do
      member do
        resources :followers
        resources :following
      end
    end

    resources :places do
      resources :comments
    end

    resources :users
    resources :districts
    resources :places
    resources :blogs
    resources :bookmarks, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_error" %><%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to following_index_path(@user) do %>
    <strong id="following" class="stat">
      <%= @user.following.size %>
    </strong>
    <%= t ".following" %>
  <% end %>
  <%= link_to followers_path(@user) do %>
    <strong id="followers" class="stat">
      <%= @user.followers.size %>
    </strong>
    <%= t ".followers" %>
  <% end %>
</div>