config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    mount Ckeditor::Engine => "/ckeditor"

    resources :blogs do
      resources :comments
    end

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/auth/:provider/callback", to: "sessions#create"
    get "/auth/failure", to: "sessions#failure"

    resources :blogs do
      resources :likes
      resources :comments
    end

    resources :users do
      member do
        resources :followers
        resources :following
      end
    end

    resources :places do
      resources :comments
    end

    resources :users
    resources :districts
    resources :places
    resources :blogs
    resources :bookmarks, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/models/place.rb
class Place < ApplicationRecord
  PLACE_ATTRIBUTE = %i(name district_id description address vote cost
    photo status).freeze
  enum status: {hotel: 0, restaurant: 1}

  has_many :bookmarks, dependent: :destroy, as: :bookmarkable
  has_many :comments, as: :commentable, dependent: :destroy

  belongs_to :district

  validates :name, presence: true,
    length: {maximum: Settings.maximum_length_name}
  validates :description, presence: true,
    length: {maximum: Settings.maximum_length_description}
  validates :address, presence: true,
    length: {maximum: Settings.maximum_length_address}
  validates :vote, presence: true,
    numericality: {greater_than_or_equal_to: Settings.minximum_vote}
  validates :cost, presence: true,
    length: {maximum: Settings.maximum_length_cost}
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  scope :find_address,
    ->(params){where "address LIKE :search", search: "%#{params}%" if params.present?}
  scope :order_by_vote, ->(params){order("vote #{params}")}
  scope :get_place, ->(place_id){where id: place_id}
  scope :get_place_by_district, ->(id){where district_id: id }
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :admin_user, except: %i(index show)
  before_action :load_place, only: %i(show edit update destroy)
  before_action :order_place, only: :index

  def index
    @blogs = Blog.sort_by_time.take(3)
    @title = t params[:status]
  end

  def new
    @place = Place.new
  end

  def show
    @blogs = Blog.sort_by_time.get_blog_by_district(@place.district_id).take(3)
    @commentable = @place
    @comment = @commentable.comments.build
  end

  def edit; end

  def create
    @place = Place.new place_params

    if @place.save
      flash[:success] = t "create_success"
      redirect_to places_path(status: @place.status)
    else
      flash[:warning] = t "create_fail"
      render :new
    end
  end

  def update
    if @place.update_attributes place_params
      flash[:success] = t "update_success"
      redirect_to places_path(status: @place.status)
    else
      render :edit
    end
  end

  def destroy
    if @place.destroy
      flash[:success] = t "delete_success"
      redirect_to places_path(status: @place.status)
    else
      flash[:danger] = t "delete_fail"
      redirect_to root_path
    end
  end

  private

  def order_place
    @places = if params[:status] == Settings.place_type
                Place.hotel.find_address(params[:search])
                     .order_by_vote(params[:order])
                     .page(params[:page])
                     .per Settings.paginate
              else
                Place.restaurant.find_address(params[:search])
                     .order_by_vote(params[:order])
                     .page(params[:page])
                     .per Settings.paginate
              end
  end

  def place_params
    params.require(:place).permit Place::PLACE_ATTRIBUTE.freeze
  end

  def load_place
    @place = Place.find_by id: params[:id]

    return if @place
    flash[:danger] = t "not_found"
    redirect_to root_url
  end

  def admin_user
    redirect_to root_url unless current_user.is_admin?
  end
end

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <h4><%= f.label :status, t(".category") %></h4>
    <%= f.select :status, options_for_select(["hotel", "restaurant"]), {prompt: t(".select")}, class: "form-control" %>
  </div>
  <div class="form-group">
    <h4><%= f.label :district_id, t(".district") %></h4>
      <%= f.select :district_id, options_for_select(District.pluck(:name, :id)),
      {prompt: t(".select")}, class:"form-control" %>
  </div>
  <div class="form-group">
    <h4><%= f.label :name, t(".name") %></h4>
    <%= f.text_field :name, class: "form-control", placeholder: t(".enter_name") %>
  </div>
  <div class="form-group">
    <h4><%= f.label :description, t(".description") %></h4>
    <%= f.text_area :description, class: "form-control", placeholder: t(".enter_description"), rows:"5" %>
  </div>
  <div class="form-group">
    <h4><%= f.label :address, t(".address") %></h4>
    <%= f.text_field :address, class: "form-control", placeholder: t(".enter_address") %>
  </div>
  <div class="form-group">
    <h4><%= f.label :vote, t(".evaluate") %></h4>
    <%= f.select :vote, options_for_select((1..5).to_a), {prompt: t(".select")}, class: "form-control" %>
  </div>
  <div class="form-group">
    <h4><%= f.label :cost, t(".cost") %></h4>
    <%= f.text_field :cost, class: "form-control", placeholder: t(".enter_cost") %>
  </div>
  <h4><%= f.label :photo, t(".photo") %></h4>
  <%= f.file_field :photo, accept: "image/jpeg,image/gif,image/png" %>
  <div class="fix_center">
    <%= f.submit t(".submit"), class:"form-btn" %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div class="row">
  <div class="col-4">
    <%= image_tag place.photo.url, class: "photo" %>
  </div>
  <div class="col-8">
    <div class="name_place">
      <%= place.name %>
    </div>
    <span class="item">
      <%= t ".evaluate" %>
    </span><% place.vote.times do %>
      <img class="fix_star" src="/assets/star1.png">
    <% end %>
    <% (5 - place.vote).times do %>
      <img class="fix_star" src="/assets/star2.png">
    <% end %><br>
    <span class="item">
      <%= t ".district" %>
    </span><%= place.district.name %><br>
    <span class="item">
      <%= t ".address" %>
    </span><%= place.address %><br>
    <span class="item">
      <%= t ".cost" %>
    </span><%= place.cost %><br>
    <%= render "bookmarks/form_bookmark", place: place %>
    <%= link_to t(".see"), place_path(place) %><br>
    <% if logged_in? && current_user.is_admin? %>
      <i class="fa fa-trash"></i>
      <%= link_to t(".delete"), place, method: :delete,
        data: { confirm: t(".sure") } %>
      <i class="fa fa-wrench"></i>
      <%= link_to t(".edit"), edit_place_path(place) %>
    <% end %>
  </div>
</div><hr>

app/views/places/_related_place.html.erb
<div>
  <% Place.get_place_by_district(@blog.district_id).take(3).each do |place| %>
      <div class="cover_photo_blog_index">
        <%= image_tag place.photo.to_s, class: "img_thumbnail" %>
      </div>
      <div class="post-article">
        <span><%= link_to place.name, place, class: "topic_blog crop_text_2" %></span>
      </div>
  <% end %>
</div>

app/views/places/edit.html.erb
<div class="fix_body">
  <div class="container">
    <div class="fix_center">
      <h1><%= t ".update" %></h1><br><br>
    </div>
    <div class="row">
      <div class="col-md-6">
        <br><img class="fix_img" src="/assets/hoguom.jpg">
      </div>
      <div class="col-md-6">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="fix_body">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <div class="fix_center">
          <h1><%= t ".search" %></h1><br><br>
        </div>
        <%= form_tag places_path, method: :get do  %>
          <% unless @places.empty? %>
            <%= hidden_field_tag :status, @places.first.status %>
          <% end %>
          <h4><%= t ".order" %></h4>
          <%= select_tag :order, options_for_select(["Desc", "Asc"]), {prompt: t(".select")} %><br><br>
          <h4><%= t ".search_address" %></h4>
          <%= search_field_tag :search, params[:search], placeholder: t(".search"), class: "form-control" %>
          <%= button_tag t(".submit"), class: "form-btn fix_btn" %><hr>
          <h5><%= t ".new_blog" %></h5>
          <% @blogs.each do |blog| %>
            <%= image_tag blog.cover_photo.to_s, class: "img_thumbnail" %>
            <%= link_to blog.topic, blog, class: "fix_topic" %><br>
            <%= t ".authors" %><%= blog.user.name %><br>
            <%= t ".posted" %><%= blog.created_at.strftime("%m-%d-%Y") %><hr>
          <% end %>
        <% end %>
      </div>
      <div class="col-8">
        <div class="fix_center">
          <h1><%= @title %></h1><br>
        </div><hr>
        <%= render @places %>
        <%= paginate @places, theme: "twitter-bootstrap-4" %>
      </div>
    </div>
  </div>
</div>

app/views/places/new.html.erb
<div class="fix_body">
  <div class="container">
    <div class="fix_center">
      <h1><%= t ".enter" %></h1><br>
    </div>
    <div class="row">
      <div class="col-md-6">
        <br><img class="fix_img" src="/assets/hoguom.jpg">
      </div>
      <div class="col-md-6">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<div class="fix_body">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <div class="name_place fix_center">
          <%= t ".review" %>
        </div><br>
        <%= @place.comments.count %> <%= t ".comment" %><br><br>
        <% if logged_in? %>
          <%= render "comments/comment_form", commentable: @commentable, comment_new: @comment, parent_id:nil %>
        <% end %>
        <%= comments_tree_for @commentable.comments.hash_tree(limit_depth: 2), @commentable, @comment %>
      </div>
      <div class="col-8">
        <div class="name_place fix_center">
          <%= @place.name %>
        </div><br>
        <%= image_tag @place.photo.url, class:"fix_img_show" %><br><br>
        <span class="item">
          <%= t ".description" %>
        </span><%= @place.description %><br>
        <span class="item">
          <%= t ".evaluate" %>
        </span><% @place.vote.times do %>
          <img class="fix_star" src="/assets/star1.png">
        <% end %>
        <% (5 - @place.vote).times do %>
          <img class="fix_star" src="/assets/star2.png">
        <% end %><br>
        <span class="item">
          <%= t ".district" %>
        </span><%= @place.district.name %><br>
        <span class="item">
          <%= t ".address" %>
        </span><%= @place.address %><br>
        <span class="item">
          <%= t ".cost" %>
        </span><%= @place.cost %><br>
      </div>
    </div><br>
    <div class="row">
      <div class="col-5 horizontal"></div>
      <div class="col-2 text-center">
        <h2><%= "Related Blogs" %></h2>

      </div>
      <div class="col-5 horizontal"></div>
         <% @blogs.each do |blog| %>
    <div class="box">
      <div class="cover_photo_blog_index">
        <%= image_tag blog.cover_photo.to_s, class: "img_thumbnail" %>
      </div>
      <div class="post-article">
        <span><%= link_to blog.topic, blog, class: "topic_blog crop_text_2" %> </span>
      </div>
    </div>
  <% end %>
    </div>
  </div>
</div>