config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    mount Ckeditor::Engine => "/ckeditor"

    resources :blogs do
      resources :comments
    end

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/auth/:provider/callback", to: "sessions#create"
    get "/auth/failure", to: "sessions#failure"

    resources :blogs do
      resources :likes
      resources :comments
    end

    resources :users do
      member do
        resources :followers
        resources :following
      end
    end

    resources :places do
      resources :comments
    end

    resources :users
    resources :districts
    resources :places
    resources :blogs
    resources :bookmarks, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_font.html.erb
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css">

app/views/layouts/_footer.html.erb
<footer class="footer footer_custom">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-4">
        <div class="static">
          <h3><%= t(".statistic") %></h3>
          <%= Place.count %>
          <%= t(".local_city") %><br>
          <%= User.count %>
          <%= t(".user") %><br>
          <%= Comment.count %>
          <%= t(".comment") %>
          <%= t(".share") %><br>
          <%= Blog.count %>
          <%= t(".checkin") %>
          <%= t(".done") %><br>
          <%#= t(".image") %>
          <%#= t(".upload") %><br>
          <%#= t(".album") %>
          <%#= t(".albumcreate") %>
        </div>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <%= link_to "https://twitter.com/?lang=vi" do %>
              <i class="fa fa-twitter"></i>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to "http://facebook.com.vn" do %>
              <i class="fa fa-facebook-f"></i>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to "https://www.skype.com/en/" do %>
              <i class="fa fa-skype"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li class="list-inline-item">
            <%= link_to t(".Privacy"), "#" %>
          </li>
          <li class="list-inline-item">
            <%= link_to t(".Terms"), "#" %>
          </li><br>
          <%= link_to image_tag("us.png", alt: "en"), locale:"en" %>
          <%= link_to image_tag("vn.png", alt: "vi"), locale:"vi" %>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= render "blogs/all_blog"  %>
<% else %>
<header class="masthead">
  <div class="container">
      <div class="intro-text">
        <div class="intro-lead-in"><%= t(".welcome") %></div>
        <div class="intro-heading text-uppercase"><%= t(".content") %></div>
        <%= link_to t(".signup"), signup_path , class: "btn btn-primary btn-xl text-uppercase js-scroll-trigger" %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<header class="header_custom">
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top " id="mainNav">
    <div class="container">
      <%= link_to t(".logo"), root_path , class: "navbar-brand js-scroll-trigger" %>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <%= t(".menu") %>
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to t(".home"), root_url, class: "nav-link js-scroll-trigger" %>
            </li>
            <li class="nav-item">
              <%= link_to t(".new"), new_blog_path, class: "nav-link js-scroll-trigger" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to t(".home"), blogs_path, class: "nav-link js-scroll-trigger" %>
            </li>
          <% end %>
          <li class="dropdown pr-2">
            <%= link_to "#", class: "dropdown-toggle fix_color", "data-toggle": "dropdown" do %>
              <%= t ".discovery" %><b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu fix_menu">
              <li><%= link_to t(".hotel"), places_path(status: :hotel) %></li>
              <li><%= link_to t(".restaurant"), places_path(status: :restaurant) %></li>
            </ul>
          </li>
          <% if logged_in? && current_user.is_admin? %>
            <li class="dropdown">
              <%= link_to "#", class: "dropdown-toggle fix_color", "data-toggle": "dropdown" do %>
                <%= t ".enter" %><b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu fix_menu">
                <li><%= link_to t(".district"), new_district_path %></li>
                <li><%= link_to t(".place"), new_place_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="nav-item">
            <% if logged_in? %>
              <li class="dropdown">
                <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
                  <% if current_user.is_admin? %>
                    <%= t ".admin" %> <b class="caret"></b>
                  <% else %>
                    <%= current_user.name %> <b class="caret"></b>
                  <% end %>
                <% end %>
                <ul class="dropdown-menu">
                  <% if current_user.is_admin? %>
                    <%= link_to t(".user"), users_path, class: "a-login"%>
                  <% end %>
                  <li>
                    <%= link_to t(".profile"), current_user,class: "a-login" %>
                  </li>
                  <% if current_user.is_login_facebook? %>
                    <li>
                      <%= link_to t(".setting"), edit_user_path(current_user),class: "a-login" %>
                    </li>
                  <% end %>
                  <li>
                    <%= link_to t(".logout"), logout_path,class: "a-login", method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li class="login-header">
                <%= link_to t(".login"), login_path ,class: "a-login"%>
              </li>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= full_title yield :title %></title>
  <%= render "layouts/default" %>
  <%= render "layouts/font"%>
</head>
<body>
  <%= render "layouts/navigation"%>
  <div class="container-body">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    
  <% end %>
  <%= yield %>
  <%= render "layouts/footer" %>
</body>
</html>